export const CANDIDATE_ROLES = [
    "Application Developer",
    "Business Analyst",
    "Cloud Architect",
    "Computer Programmer",
    "Computer Support Specialist",
    "Cybersecurity Analyst",
    "Data Analyst",
    "Data Scientist",
    "Database Administrator",
    "DevOps Engineer",
    "Enterprise Architect",
    "Front End Developer",
    "Full Stack Developer",
    "Help Desk Technician",
    "Information Security Analyst",
    "IT Manager",
    "IT Project Manager",
    "IT Support Engineer",
    "Java Developer",
    "Network Administrator",
    "Network Engineer",
    "Product Manager - IT",
    "Quality Assurance Engineer",
    "Scrum Master",
    "Security Engineer",
    "Software Engineer",
    "Solutions Architect",
    "SQL Developer",
    "System Administrator",
    "Systems Analyst",
    "Technical Support Specialist",
    "UI/UX Designer",
    "Web Developer",
    "AI/Machine Learning Engineer",
    "Blockchain Developer",
    "Chief Information Officer",
    "Chief Technology Officer",
    "Computational Linguist",
    "Computer Hardware Engineer",
    "Content Manager - IT",
    "CRM Developer",
    "Data Architect",
    "Digital Marketing Specialist - IT",
    "Embedded Systems Engineer",
    "Game Developer",
    "GIS Specialist",
    "IT Auditor",
    "IT Consultant",
    "IT Trainer",
    "Mobile Application Developer"
];