openapi: 3.0.0
info:
  title: Interview Scheduler API
  description: API documentation for Interview Scheduler application
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/users:
    get:
      summary: Get all users
      responses:
        '200':
          description: Successful response
  /api/users/{userId}:
    get:
      summary: Get user by ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: ID of the user to retrieve
      responses:
        '200':
          description: Successful response
  /api/technologies:
    get:
      summary: Get all technologies
      responses:
        '200':
          description: Successful response
  /api/candidates:
    get:
      summary: Get all candidates
      responses:
        '200':
          description: Successful response
  /api/interviews:
    get:
      summary: Get all interviews
      responses:
        '200':
          description: Successful response
  /api/notes:
    get:
      summary: Get all notes
      responses:
        '200':
          description: Successful response
